#!/bin/bash

# optimize -- Revision: 1X1 -- by WsoumOS (https://os.wsoum.ml/)
# (GNU/General Public License version 3.0)

optimizer () {
  cp /etc/apt/sources.list /etc/apt/sources.list.b4optimize
  rm /etc/apt/sources.list
  cp /usr/share/WsoumOS1X1/wsoumos1X1/sources/sources.bullseye /etc/apt/sources.list
  #cp /usr/share/WsoumOS1X1/wsoumos1X1/sources/sources.buster /etc/apt/sources.list
  cp /usr/share/WsoumOS1X1/wsoumos1X1/sources/apt.conf /etc/apt/apt.conf
  apt -y update
}

optimizer

done

# Disclaimer:

# THIS SOFTWARE IS PROVIDED BY WSOUMOS “AS IS” AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
# EVENT SHALL WSOUMOS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
# PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
# IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
